apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-app
  labels:
    app: insurance-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-app
  template:
    metadata:
      labels:
        app: insurance-app
    spec:
      containers:
        - name: insurance-app-container
          image: akki5175/insurance-app:latest
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: insurance-service
spec:
  type: NodePort
  selector:
    app: insurance-app
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30082
