apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-deployment
  labels:
    app: insurance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insurance
  template:
    metadata:
      labels:
        app: insurance
    spec:
      containers:
        - name: insurance-container
          image: akki5175/insurancee:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: insurance-care-service
spec:
  selector:
    app: insurance
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30082
