apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-care-deployment
  labels:
    app: health-care
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health-care
  template:
    metadata:
      labels:
        app: health-care
    spec:
      containers:
        - name: health-care-container
          image: akki5175/health_care:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: health-care-service
spec:
  selector:
    app: health-care
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30082
